import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function POST() {
  try {
    let user = await prisma.user.findFirst();
    if (!user) {
      user = await prisma.user.create({ data: { email: "demo@goalforge.ai", name: "Demo User" } });
    }

    const goal = await prisma.goal.create({
      data: {
        title: "Build the Ultimate AI Startup",
        description: "Win the Vibe2Ship Hackathon and secure seed funding.",
        deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // 5 days from now
        riskScore: "Critical",
        completionProb: 45,
        bufferDays: 1,
        userId: user.id,
      }
    });

    const workflow = await prisma.workflow.create({ data: { goalId: goal.id } });

    // Premium simulated nodes
    const nodesData = [
      { id: 'n1', title: 'Market Research', type: 'task', agentType: 'RESEARCH', priority: 'HIGH', estimatedHours: 4, criticalPath: false, x: 250, y: 50 },
      { id: 'n2', title: 'Architecture Design', type: 'milestone', agentType: 'EXECUTE', priority: 'CRITICAL', estimatedHours: 8, criticalPath: true, x: 250, y: 250 },
      { id: 'n3', title: 'Develop MVP', type: 'task', agentType: 'EXECUTE', priority: 'CRITICAL', estimatedHours: 24, criticalPath: true, x: 250, y: 450 },
      { id: 'n4', title: 'Final Review', type: 'task', agentType: 'REVIEW', priority: 'HIGH', estimatedHours: 2, criticalPath: false, x: 250, y: 650 },
    ];

    const dbNodes = [];
    for (const n of nodesData) {
      const dbNode = await prisma.node.create({
        data: {
          workflowId: workflow.id,
          title: n.title,
          description: "Generated by Demo Mode Seeder.",
          type: n.type,
          agentType: n.agentType,
          priority: n.priority,
          estimatedHours: n.estimatedHours,
          criticalPath: n.criticalPath,
          positionX: n.x,
          positionY: n.y,
        }
      });
      dbNodes.push({ originalId: n.id, dbId: dbNode.id });
    }

    // Edges
    const edgesData = [
      { source: 'n1', target: 'n2' },
      { source: 'n2', target: 'n3' },
      { source: 'n3', target: 'n4' },
    ];

    for (const e of edgesData) {
      const sourceDbId = dbNodes.find(n => n.originalId === e.source)?.dbId;
      const targetDbId = dbNodes.find(n => n.originalId === e.target)?.dbId;
      if (sourceDbId && targetDbId) {
        await prisma.edge.create({
          data: {
            workflowId: workflow.id,
            sourceId: sourceDbId,
            targetId: targetDbId,
          }
        });
      }
    }

    return NextResponse.json({ success: true, message: "Demo workflow seeded successfully.", workflowId: workflow.id });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
