import { GoogleGenAI } from '@google/genai';
import { prisma } from '@/lib/prisma';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function optimizeWorkflow(workflowId: string) {
  const workflow = await prisma.workflow.findUnique({
    where: { id: workflowId },
    include: { nodes: true, edges: true, goal: true }
  });

  if (!workflow) throw new Error("Workflow not found");

  const prompt = `You are an elite Workflow Optimization AI.
Analyze the following goal and its current execution graph (nodes and edges).
Goal: "${workflow.goal.title}"
Nodes: ${JSON.stringify(workflow.nodes.map((n: any) => ({ id: n.id, title: n.title, status: n.status })))}
Edges: ${JSON.stringify(workflow.edges.map((e: any) => ({ source: e.sourceId, target: e.targetId })))}

Identify any bottlenecks, suggest re-prioritization, or propose a smarter path.
Output your optimization strategy in a clear, concise Markdown format.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    if (!response.text) {
      throw new Error("No response generated by Optimization Agent.");
    }

    return response.text;
  } catch (error) {
    console.error("OptimizationAgent failed:", error);
    throw error;
  }
}
